NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.storage.cloud-labs.io-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.storage.cloud-labs.io-cert.pem
    OrganizationalUnitIdentifier: peer
