version: '3'
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  baas:
    external:
      name: baas
volumes:
  explorerdb:
  walletstore:
services:
  explorerdb:
    image: hyperledger/explorer-db:latest
    hostname: explorerdb.cloud-labs.io
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=fabricexplorer
      - DATABASE_PASSWORD=fabricexplorer
    networks:
      baas:
        aliases:
          - explorerdb.cloud-labs.io
    volumes:
      - explorerdb:/var/lib/postgresql/data
      - $PWD/hyperledger-fabric-network/artifacts/scripts/createdb.sh:/docker-entrypoint-initdb.d/createdb.sh
  explorer:
    image: hyperledger/explorer:latest
    hostname: explorer.cloud-labs.io
    environment:
      - DATABASE_HOST=explorerdb.cloud-labs.io
      - DATABASE_USERNAME=fabricexplorer
      - DATABASE_PASSWD=fabricexplorer
      - DISCOVERY_AS_LOCALHOST=false
    command: sh -c "sleep 16&& node /opt/explorer/main.js && tail -f /dev/null"
    networks:
      traefik_proxy:
        aliases:
          - explorer.cloud-labs.io
      baas:
        aliases:
          - explorer.cloud-labs.io
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik_proxy
        - traefik.http.services.explorer.loadbalancer.server.port=8080
        - traefik.http.routers.explorer.rule=Host(`explorer.cloud-labs.io`)
    volumes:
      - walletstore:/opt/wallet
      - $PWD/hyperledger-fabric-network/artifacts/config/explorer/config.json:/opt/explorer/app/platform/fabric/config.json
      - $PWD/hyperledger-fabric-network/artifacts/config/explorer/cloud-labs.json:/opt/explorer/app/platform/fabric/cloud-labs.json
      - $PWD/hyperledger-fabric-network/artifacts/crypto-config:/tmp/crypto